controllers:
    # resource: routing.controllers
    # as described in https://symfony.com/blog/new-in-symfony-7-4-attribute-improvements#route-attribute-auto-registration
    # doesn't seem to work yet gjuric/i18n-routing-bundle
    # therefore keep as
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
